ifneq (,$(filter gnrc_netdev_default netdev_default,$(USEMODULE)))
  USEMODULE += at86rf233
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif

ifneq (,$(filter auto_init_saul,$(USEMODULE)))
  USEMODULE += tmp006
  USEMODULE += hdc1000
  USEMODULE += fxos8700
  USEMODULE += apds9007
  USEMODULE += ekmb
  USEMODULE += pulse_counter
endif
